import fs from 'fs';

/**
 * Generate an HTML comparison report.
 * @param {object} comparison - Output from compareDocuments()
 * @param {object} doc1 - Old document metadata
 * @param {object} doc2 - New document metadata
 * @param {object} stats1 - Old document stats
 * @param {object} stats2 - New document stats
 * @param {string} outputPath - Path to write the HTML file
 */
export function generateHTMLReport(comparison, doc1, doc2, stats1, stats2, outputPath) {
  const html = buildHTML(comparison, doc1, doc2, stats1, stats2);
  fs.writeFileSync(outputPath, html, 'utf8');
}

function esc(text) {
  return String(text || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildHTML(comparison, doc1, doc2, stats1, stats2) {
  const { summary, sectionDiffs } = comparison;

  const totalRowChanges = countRowChanges(sectionDiffs);

  let sectionsHTML = '';
  for (const sd of sectionDiffs) {
    sectionsHTML += renderSectionDiff(sd, doc1, doc2);
  }

  return `<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PDF Compare: ${esc(doc1.version)} vs ${esc(doc2.version)}</title>
  <style>${CSS}</style>
</head>
<body>
  <header>
    <h1>IFTSTA AHB Comparison Report</h1>
    <p class="subtitle">${esc(doc1.version)} &rarr; ${esc(doc2.version)}</p>
  </header>

  <section class="summary">
    <h2>Overview</h2>
    <div class="cards">
      <div class="card">
        <h3>Old Version</h3>
        <dl>
          <dt>Version</dt><dd>${esc(doc1.version)}</dd>
          <dt>File</dt><dd>${esc(doc1.filename)}</dd>
          <dt>Pages</dt><dd>${doc1.pageCount}</dd>
          <dt>Sections</dt><dd>${stats1.sectionCount}</dd>
          <dt>Data Rows</dt><dd>${stats1.rowCount}</dd>
        </dl>
      </div>
      <div class="card">
        <h3>New Version</h3>
        <dl>
          <dt>Version</dt><dd>${esc(doc2.version)}</dd>
          <dt>File</dt><dd>${esc(doc2.filename)}</dd>
          <dt>Pages</dt><dd>${doc2.pageCount}</dd>
          <dt>Sections</dt><dd>${stats2.sectionCount}</dd>
          <dt>Data Rows</dt><dd>${stats2.rowCount}</dd>
        </dl>
      </div>
    </div>

    <h3>Section Changes</h3>
    <div class="stat-row">
      <span class="stat modified">${summary.modified} Modified</span>
      <span class="stat added">${summary.added} Added</span>
      <span class="stat removed">${summary.removed} Removed</span>
      <span class="stat unchanged">${summary.unchanged} Unchanged</span>
    </div>

    <h3>Row Changes</h3>
    <div class="stat-row">
      <span class="stat modified">${totalRowChanges.modified} Modified</span>
      <span class="stat added">${totalRowChanges.added} Added</span>
      <span class="stat removed">${totalRowChanges.removed} Removed</span>
      <span class="stat unchanged">${totalRowChanges.unchanged} Unchanged</span>
    </div>
  </section>

  <section class="details">
    <h2>Section Details</h2>
    <p class="filter-hint">Click section headers to expand/collapse.</p>
    ${sectionsHTML}
  </section>

  <footer>
    <p>Generated by PDFCompare on ${new Date().toISOString().slice(0, 16).replace('T', ' ')}</p>
  </footer>

  <script>${JS}</script>
</body>
</html>`;
}

function countRowChanges(sectionDiffs) {
  const counts = { added: 0, removed: 0, modified: 0, unchanged: 0 };
  for (const sd of sectionDiffs) {
    for (const rd of sd.rows || []) {
      counts[rd.type] = (counts[rd.type] || 0) + 1;
    }
  }
  return counts;
}

function renderSectionDiff(sd, doc1, doc2) {
  const typeClass = sd.type;
  const typeLabel = sd.type.charAt(0).toUpperCase() + sd.type.slice(1);
  const pruef = esc(sd.pruefidentifikator);

  const title = sd.sectionOld?.title || sd.sectionNew?.title || sd.section?.title || '';

  const rowStats = { added: 0, removed: 0, modified: 0, unchanged: 0 };
  for (const rd of sd.rows || []) {
    rowStats[rd.type] = (rowStats[rd.type] || 0) + 1;
  }

  const hasRowChanges = rowStats.added + rowStats.removed + rowStats.modified > 0;
  const collapsed = sd.type === 'unchanged' ? 'collapsed' : '';

  let content = '';

  // Meta changes
  if (sd.metaChanges?.length) {
    content += `<div class="meta-changes"><h4>Section Metadata Changes</h4><table class="meta-table">
      <tr><th>Field</th><th>Old</th><th>New</th></tr>`;
    for (const mc of sd.metaChanges) {
      content += `<tr>
        <td>${esc(mc.field)}</td>
        <td class="old-val">${esc(mc.old)}</td>
        <td class="new-val">${esc(mc.new)}</td>
      </tr>`;
    }
    content += `</table></div>`;
  }

  // Row table
  if (sd.rows?.length) {
    content += renderRowTable(sd.rows, sd.type);
  }

  return `
  <div class="section-diff ${typeClass} ${collapsed}">
    <div class="section-header" onclick="toggleSection(this)">
      <span class="toggle-icon">${collapsed ? '\u25B6' : '\u25BC'}</span>
      <span class="badge ${typeClass}">${typeLabel}</span>
      <span class="pruef">Pr\u00FCfidentifikator: ${pruef}</span>
      ${title ? `<span class="section-title">${esc(title)}</span>` : ''}
      <span class="row-summary">
        ${rowStats.modified ? `<span class="mini-stat modified">${rowStats.modified} mod</span>` : ''}
        ${rowStats.added ? `<span class="mini-stat added">${rowStats.added} add</span>` : ''}
        ${rowStats.removed ? `<span class="mini-stat removed">${rowStats.removed} rem</span>` : ''}
      </span>
    </div>
    <div class="section-body">
      ${content}
    </div>
  </div>`;
}

function renderRowTable(rowDiffs, sectionType) {
  // For added/removed sections, show simple table
  if (sectionType === 'added' || sectionType === 'removed') {
    return renderSimpleTable(rowDiffs, sectionType);
  }

  // For modified sections, show diff table
  let html = `<table class="diff-table">
    <thead>
      <tr>
        <th class="col-status">Status</th>
        <th class="col-sg">SG</th>
        <th class="col-code">Code</th>
        <th class="col-de">DE</th>
        <th class="col-desc">Beschreibung</th>
        <th class="col-s1">Status 1</th>
        <th class="col-s2">Status 2</th>
        <th class="col-bed">Bedingung</th>
      </tr>
    </thead>
    <tbody>`;

  for (const rd of rowDiffs) {
    if (rd.type === 'unchanged') {
      html += renderUnchangedRow(rd.row);
    } else if (rd.type === 'added') {
      html += renderAddedRow(rd.row);
    } else if (rd.type === 'removed') {
      html += renderRemovedRow(rd.row);
    } else if (rd.type === 'modified') {
      html += renderModifiedRow(rd);
    }
  }

  html += `</tbody></table>`;
  return html;
}

function renderSimpleTable(rowDiffs, type) {
  const cssClass = type === 'added' ? 'row-added' : 'row-removed';

  let html = `<table class="diff-table">
    <thead>
      <tr>
        <th class="col-sg">SG</th>
        <th class="col-code">Code</th>
        <th class="col-de">DE</th>
        <th class="col-desc">Beschreibung</th>
        <th class="col-s1">Status 1</th>
        <th class="col-s2">Status 2</th>
        <th class="col-bed">Bedingung</th>
      </tr>
    </thead>
    <tbody>`;

  for (const rd of rowDiffs) {
    const r = rd.row;
    html += `<tr class="${cssClass}">
      <td>${esc(r.segmentGroup)}</td>
      <td>${esc(r.segmentCode)}</td>
      <td>${esc(r.dataElement)}</td>
      <td>${esc(r.beschreibung)}</td>
      <td>${esc(r.statusCol1)}</td>
      <td>${esc(r.statusCol2)}</td>
      <td>${esc(r.bedingung)}</td>
    </tr>`;
  }

  html += `</tbody></table>`;
  return html;
}

function renderUnchangedRow(r) {
  return `<tr class="row-unchanged">
    <td><span class="badge unchanged">-</span></td>
    <td>${esc(r.segmentGroup)}</td>
    <td>${esc(r.segmentCode)}</td>
    <td>${esc(r.dataElement)}</td>
    <td>${esc(r.beschreibung)}</td>
    <td>${esc(r.statusCol1)}</td>
    <td>${esc(r.statusCol2)}</td>
    <td>${esc(r.bedingung)}</td>
  </tr>`;
}

function renderAddedRow(r) {
  return `<tr class="row-added">
    <td><span class="badge added">+</span></td>
    <td>${esc(r.segmentGroup)}</td>
    <td>${esc(r.segmentCode)}</td>
    <td>${esc(r.dataElement)}</td>
    <td>${esc(r.beschreibung)}</td>
    <td>${esc(r.statusCol1)}</td>
    <td>${esc(r.statusCol2)}</td>
    <td>${esc(r.bedingung)}</td>
  </tr>`;
}

function renderRemovedRow(r) {
  return `<tr class="row-removed">
    <td><span class="badge removed">&minus;</span></td>
    <td>${esc(r.segmentGroup)}</td>
    <td>${esc(r.segmentCode)}</td>
    <td>${esc(r.dataElement)}</td>
    <td>${esc(r.beschreibung)}</td>
    <td>${esc(r.statusCol1)}</td>
    <td>${esc(r.statusCol2)}</td>
    <td>${esc(r.bedingung)}</td>
  </tr>`;
}

function renderModifiedRow(rd) {
  const changedFields = new Set(rd.changes.map(c => c.field));

  function cell(field, oldVal, newVal) {
    if (changedFields.has(field)) {
      return `<td class="cell-changed">
        <div class="old-val">${esc(oldVal)}</div>
        <div class="new-val">${esc(newVal)}</div>
      </td>`;
    }
    return `<td>${esc(newVal)}</td>`;
  }

  const o = rd.rowOld;
  const n = rd.rowNew;

  return `<tr class="row-modified">
    <td><span class="badge modified">~</span></td>
    ${cell('segmentGroup', o.segmentGroup, n.segmentGroup)}
    ${cell('segmentCode', o.segmentCode, n.segmentCode)}
    ${cell('dataElement', o.dataElement, n.dataElement)}
    ${cell('beschreibung', o.beschreibung, n.beschreibung)}
    ${cell('statusCol1', o.statusCol1, n.statusCol1)}
    ${cell('statusCol2', o.statusCol2, n.statusCol2)}
    ${cell('bedingung', o.bedingung, n.bedingung)}
  </tr>`;
}

// --- Embedded CSS ---
const CSS = `
  :root {
    --green: #22863a;
    --green-bg: #dcffe4;
    --red: #cb2431;
    --red-bg: #ffeef0;
    --yellow: #b08800;
    --yellow-bg: #fff8c5;
    --gray: #586069;
    --gray-bg: #f6f8fa;
    --border: #e1e4e8;
  }

  * { box-sizing: border-box; margin: 0; padding: 0; }

  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
    line-height: 1.5;
    color: #24292e;
    max-width: 1400px;
    margin: 0 auto;
    padding: 20px;
    background: #fff;
  }

  header {
    border-bottom: 2px solid var(--border);
    padding-bottom: 16px;
    margin-bottom: 24px;
  }
  header h1 { font-size: 28px; }
  header .subtitle { color: var(--gray); font-size: 18px; }

  h2 { margin: 24px 0 12px; font-size: 22px; }
  h3 { margin: 16px 0 8px; font-size: 16px; }
  h4 { margin: 12px 0 6px; font-size: 14px; }

  .cards {
    display: flex;
    gap: 16px;
    flex-wrap: wrap;
  }
  .card {
    flex: 1;
    min-width: 280px;
    border: 1px solid var(--border);
    border-radius: 6px;
    padding: 16px;
    background: var(--gray-bg);
  }
  .card h3 { margin-top: 0; }
  .card dl { display: grid; grid-template-columns: auto 1fr; gap: 4px 12px; }
  .card dt { font-weight: 600; color: var(--gray); }

  .stat-row {
    display: flex;
    gap: 12px;
    flex-wrap: wrap;
    margin: 8px 0 16px;
  }
  .stat {
    padding: 6px 14px;
    border-radius: 20px;
    font-weight: 600;
    font-size: 14px;
  }
  .stat.added { background: var(--green-bg); color: var(--green); }
  .stat.removed { background: var(--red-bg); color: var(--red); }
  .stat.modified { background: var(--yellow-bg); color: var(--yellow); }
  .stat.unchanged { background: var(--gray-bg); color: var(--gray); }

  .filter-hint { color: var(--gray); font-size: 13px; margin-bottom: 12px; }

  .section-diff {
    border: 1px solid var(--border);
    border-radius: 6px;
    margin-bottom: 12px;
    overflow: hidden;
  }
  .section-diff.added { border-left: 4px solid var(--green); }
  .section-diff.removed { border-left: 4px solid var(--red); }
  .section-diff.modified { border-left: 4px solid var(--yellow); }
  .section-diff.unchanged { border-left: 4px solid var(--border); }

  .section-header {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 10px 14px;
    background: var(--gray-bg);
    cursor: pointer;
    user-select: none;
    flex-wrap: wrap;
  }
  .section-header:hover { background: #eef0f2; }

  .toggle-icon { font-size: 12px; width: 16px; text-align: center; }
  .pruef { font-weight: 600; font-size: 14px; }
  .section-title { color: var(--gray); font-size: 13px; }

  .badge {
    display: inline-block;
    padding: 2px 8px;
    border-radius: 12px;
    font-size: 12px;
    font-weight: 600;
    text-transform: uppercase;
  }
  .badge.added { background: var(--green-bg); color: var(--green); }
  .badge.removed { background: var(--red-bg); color: var(--red); }
  .badge.modified { background: var(--yellow-bg); color: var(--yellow); }
  .badge.unchanged { background: var(--gray-bg); color: var(--gray); }

  .mini-stat { font-size: 11px; padding: 1px 6px; border-radius: 8px; }
  .mini-stat.modified { background: var(--yellow-bg); color: var(--yellow); }
  .mini-stat.added { background: var(--green-bg); color: var(--green); }
  .mini-stat.removed { background: var(--red-bg); color: var(--red); }

  .row-summary { margin-left: auto; display: flex; gap: 6px; }

  .section-body { padding: 0; }
  .collapsed .section-body { display: none; }

  .meta-changes { padding: 12px 14px; }
  .meta-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 13px;
  }
  .meta-table th, .meta-table td {
    padding: 4px 8px;
    border: 1px solid var(--border);
    text-align: left;
  }
  .meta-table .old-val { background: var(--red-bg); }
  .meta-table .new-val { background: var(--green-bg); }

  .diff-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 12px;
  }
  .diff-table th {
    background: var(--gray-bg);
    padding: 6px 8px;
    border: 1px solid var(--border);
    text-align: left;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    position: sticky;
    top: 0;
  }
  .diff-table td {
    padding: 4px 8px;
    border: 1px solid var(--border);
    vertical-align: top;
    word-break: break-word;
  }

  .col-status { width: 50px; }
  .col-sg { width: 50px; }
  .col-code { width: 50px; }
  .col-de { width: 60px; }
  .col-desc { width: 25%; }
  .col-s1 { width: 15%; }
  .col-s2 { width: 15%; }
  .col-bed { width: 25%; }

  .row-added { background: var(--green-bg); }
  .row-removed { background: var(--red-bg); }
  .row-modified { background: var(--yellow-bg); }
  .row-unchanged { background: #fff; }
  .row-unchanged:hover { background: #f9f9f9; }

  .cell-changed {
    background: #fffbe6;
    position: relative;
  }
  .cell-changed .old-val {
    text-decoration: line-through;
    color: var(--red);
    font-size: 11px;
  }
  .cell-changed .new-val {
    color: var(--green);
    font-weight: 500;
  }

  footer {
    margin-top: 32px;
    padding-top: 16px;
    border-top: 1px solid var(--border);
    color: var(--gray);
    font-size: 13px;
  }

  @media (max-width: 900px) {
    .diff-table { font-size: 11px; }
    .diff-table th, .diff-table td { padding: 3px 4px; }
  }
`;

// --- Embedded JS for interactivity ---
const JS = `
  function toggleSection(header) {
    const section = header.closest('.section-diff');
    section.classList.toggle('collapsed');
    const icon = header.querySelector('.toggle-icon');
    icon.textContent = section.classList.contains('collapsed') ? '\\u25B6' : '\\u25BC';
  }
`;
